aml-development/ozp-backend

ozpcenter/tests/test_utils.py
ozpcenter/utils.py

fix(Login):  Allow periods, double-quotes and backticks in usernames.

---

ozpcenter/api/listing/model_access.py

prior behavior: duplicates were returning from the similar endpoint
desired behavior: no duplicates returned from the similar endpoint
To test:  GET http://localhost:8001/api/listing/1/similar/

corrected similar listings returning duplicates

---

ozpcenter/api/storefront/model_access.py

Easiest way to test would be to look at the results from /api/storefront and see how many results are in {featured:[]}
@mleeBoeing @mannyrivera2010 @lsemesky

Removing the limit for Featured Listings in Center per AMLNG-414

---

ozpcenter/recommend/graph.py

Please review: 
@skhtet 
@J-Fid
@rkenyon1969 
@blynch11p
The change is needed to check for the possible None out_vertex_id that might result from calling add_edge with no outer vertex available.
Without the check, if the vertex_instance is None then an error will be thrown.
A warning log message will result in the situation, but should not cause issues with the code.
(To Test commented code in graph.py should be un-commented to see warning log messages and to see issue just un-comment the vertex_instance assignment)

Added Check for vertex edge being None

---

ozpcenter/api/storefront/model_access.py

Please Review the changes that resolve a reordering of the bookmarks on retrieval compared to what they were supposed to be when ranked.  This change causes the rank to be preserved when retrieving recommended list.
To Test:
Pull Main Branch and run: make recommend
Then check out the recommended list for bettafish user and make note of all of the apps that are recommended
Pull recommender_fix branch and run: make recommend
Then check out the recommended list for the same user and it should be different
(If more detail is needed add a print statement below the lazy loading under the get_storefront() to print out the list of recommendations and add another print statement to when the recommendation is being stored in save_to_db() after the appending to the batch_list call.  Then compare the …

Fix ordering of recommendations to original scoring order

---

ozpcenter/api/notification/model_access.py
ozpcenter/api/notification/tests/test_api_notification.py

Fix for active notification bug where notifications weren't being sorted by creation date

fix(notifications): Sort notifications by created date

---

ozpcenter/recommend/recommend.py

Please Review the changes for the changes that have added categories to the items being recommended.
The Categories are determined by the recommended and bookmarked listings in a user profile and then Elasticsearch uses those items to find users with similar listings in their profiles.  It then ranks the listings based on reviews of greater than 3.5 to return the results.
To test:  (SEE UPDATE AT END)
Run make recommend_es_user
Use bettafish user and a list of listings should come back for the recommended list then review a couple of the apps that are not in the recommended list and give high ratings > 3.  Run make recommend_es_user again
Look at the results and should notice apps from the same category appear.
(Ex. No Jobspot was showing up, so I reviewed Jobspot 1 and Jpbspot 9 and gave …

ES Recommendation Engine added categories to items to look for and increased ratings value to 3.5

---

ozpcenter/recommend/recommend.py

Per @skhtet request, I am changing the the boost value from 10 to 2 for the Elasticsearch query.
Please review:
@skhtet 
@J-Fid 
@mleeBoeing 
On the development setup may not notice differences since the baseline might drown out the results.  Need to verify with debug statements if results do not show up as expected.  Use bettafish as the user.

Boost Value change from 10 to 2 for ratings for ES Recommendation Engine

---

ozpcenter/api/listing/serializers.py

re-added the fields you requested @blynch11p As far as I could tell the small/large icons weren't needed to bookmark from the listing tile

added needed fields for bookmarking and display

---

ozpcenter/api/storefront/model_access.py
ozpcenter/recommend/recommend.py

Please review changes that normalize the results for the recommendations.  This will allow us to have all of the results inline:
@skhtet 
@blynch11p 
@rkenyon1969 
Changes were also made during testing for reducing the boost rating from 2 to 1 for rating and also improved the results returned from content filtering.
Here is the how to verify the results:
To Evaluate recommendation normalization (Based on original apps that have been used and will change if new apps are added):
Observe the raw_scores and they should all be in the same range without the other scores and not be too out of the area 
> make dev (Stop the backend after it starts running)
> make recommend
> make run_es
check recommendations returned by going to:
http://(Address of …

Recommend optimize - Optimization to have all of the recommendations come out at the same level

---

ozpcenter/api/listing/elasticsearch_util.py

The title will be preferred for matching over other items.  The order will be based on the scoring that is returned and may not necessarily be in alphabetical order.
This needs to be confirmed that it resolves ticket number ALMNG-206 before completing the task.  @skhtet please confirm that the issue is resolved with the fix.  Might have to manually enter it in to see the results.
Please review:
@skhtet 
@blynch11p 
@rkenyon1969

Title priority feature to prefer titles over other values first.

---

ozpcenter/api/listing/model_access.py
ozpcenter/models.py
tests/ozpcenter_api/test_api_review.py

Add function call to add new review creations to activity log.
Create test for activity log for new reviews created.
AMLNG-786
As an Admin, I would like to see new listing reviews appear in ListingMngmt>Recent Activity to facilitate Admin notification of posted comments.
• when a user submits review a summary will appear in ListingMngmt>Recent Activity
• the summary will include a link to the review tab of the reviewed listing
• similar to when a review is deleted
Test functionality by pulling https://github.com/aml-development/ozp-center/tree/New_Recent_Activity_entry
After creating a review, there will be an entry in /dist/#/user-management/recent-activity
@aml-development/ozp-backend-team …

feat(activity log): add new review to activity log

---

ozpcenter/api/listing/model_access.py
tests/ozpcenter_api/test_api_notification.py

AMLNG-828
A Listing was rated, the notification was sent and received by the owner.
The owner responded to the review.
A notification was received by the owner saying "A user has rated [listing] 1 star"
Notifications will not send if a review response is created. Notifications will still send if a new review is created.
Login as bigbrother in one window. Login as jones in a different window. As jones, open up 'Acoustic Guitar' listing and respond to one of the reviews. If you go back to bigbrother, you should see no new notifications. Go back to jones and create a new review for the listing with 5 stars. Log back into bigbrother, you should see a new notifications regarding the new review jones has created.
**Please …

fix(review): fix bug where notifications get sent on review responses

---

ozpcenter/api/listing/serializers.py
tests/ozpcenter_api/test_api_storefront.py

AMLNG-798
Pre-req - Define system and usage requirements in an App Listing. In Profile Settings , Enable the option Show Launch Requirements Notice
Go to Homepage
From Thumbnail view, Launch App from thumbnail view
RESULTS - Sys/Usage requirements pop up displays without the actual system / usage requirements.
EXPECTED RESULTS - Sys/usage requirements from pre-requisites should display on the this pop up.
Open Quick View Modal
Launch App
RESULTS - Sys/usage requirements from the prerequisites display on the pop up as they should.
Pull amlng798 from ozp-backend
Pull amlng798 from ozp-center
**Checklist**

fix(launch popup): show requirements information

---

ozpcenter/api/listing/views.py
tests/ozpcenter_api/test_api_listing.py

AMLNG-858
As a user, I would like all Listing Management tabs to have sort order dropdown option to reorder results and the default sort order to be last modified.
- when a user clicks on sub tab all results will have the same sort order
- sort order will be last modified
- each tab will have sort order dropdown option to reorder results
For now, the sort options are Last Modified, Newest, Title: A to Z, Title: Z to A, Rating: Low to High, Rating: High to Low, Status.  If no sort option is selected, the backend sort defaults to last modified.
Pull `listing_default_sort` from ozp-backend
Pull `listing_mgmt_sortable_grid` from ozp-center
Go to Listing Management
Verify Acceptance Criteria on the list view of both the …

feat(listing management): add ability to sort list view

---

ozpcenter/api/library/model_access.py
tests/ozpcenter_model_access/test_library.py

Fix for when listing is added to the library, it is inserted last into the list.
Adds tests to check for correct ordering of listings added to library.
Closes #AMLNG-699
AMLNG-699
HUD Screen should display apps in a consistent order
STR-
pre-req - Create 2 folders in HUD containing a couple bookmarked items.  Leave a few bookmarked items not in folders.
NOTE The HUD screen reflects the folders first and the remaining bookmarked listings thereafter
From Center, Bookmark a new App listing or two
Go to HUD Screen
RESULTS - The HUD Screen displays a folder first, then places the newly added bookmarked items next then the remaining folder(s), with the remaining bookmarked apps last.
EXPECTED RESULTS - The HUD screen should display folders first then remaining bookmarked …

fix(library): Add Order to Library Creation

---

ozpcenter/api/listing/views.py
tests/ozpcenter_api/test_api_listing.py

AMLNG-801
When I look at an org's listing, the URL contains the organization's title.  Instead, it should use the organization's short name to prevent spaces in the URL.
Log in as an Org Steward (ie julia)
Go to Listing Management
Select a tab corresponding to an organization
1) Ensure the URL contains the org's short name instead of the title
2) Ensure the listings are filtered by org appropriately and the counts are correct (both table and grid views).  Test sidebar filters too.
3) Ensure that getting to the tab automatically (ie via the Recent Activity Sidebar filters) follows 1-2 as well.
Manually change the URL as follows:
4) Changing the URL from org short name to org title gives an unauthorized alert message and redirects to the …

fix(listing api): use org short name instead of title for listing filter

---

ozpcenter/api/library/model_access.py
tests/ozpcenter_api/test_api_library.py

Fixes issue where the add listing API will add multiple of the same listing to existing folder.
This has become more apparent due to the new undelete feature.
Closes# AMLNG-887
If a user has a bookmark folder (Animals) and goes to the URL to add/share a bookmark folder of the same name, with the same bookmarks, those bookmarks are duplicated, rather than just adding new ones. The duplicates are unnecessary, and can cause issues with page reloading.
A shared bookmark folder link will not duplicate bookmarks the user already has in a folder of the same name.
Pull this branch.
Go into a folder and send a share notification to another user.
Log in as another user and clicking the button in the share notification.
Delete …

fix(library): fix for import_bookmarks

---

ozpcenter/api/listing/observers.py
tests/ozpcenter_api/test_api_notification.py

This removes the notification for users when a listing's owners
are modified.
Closes #AMLOS-450
As a user, I do not need to receive a notification when a listing owner change is made
-  review recipients of notification of listing owner change 
-  User who bookmarked listing does not receive notification when if listing owner change
Pull this repo. 
Log in as bigbrother and johnson.
As johnson bookmark  any listing.
As bigbrother, open that listing and change the title and add an owner. 
Check that johnson receives a notification about a title change but not an owner change.
**Checklist**

fix(notification): listing modification notification

---

ozp/urls.py
ozpcenter/api/agency/urls.py
ozpcenter/api/category/urls.py
ozpcenter/api/contact_type/urls.py
ozpcenter/api/image/urls.py
ozpcenter/api/intent/urls.py
ozpcenter/api/library/urls.py
ozpcenter/api/listing/observers.py
ozpcenter/api/listing/urls.py
ozpcenter/api/notification/urls.py
ozpcenter/api/profile/urls.py
ozpcenter/api/storefront/urls.py
ozpcenter/api/subscription/urls.py
ozpcenter/models.py
ozpcenter/urls.py
ozpiwc/api/data/urls.py
ozpiwc/api/intent/urls.py
ozpiwc/api/system/urls.py
ozpiwc/urls.py
performance_testing/listing_update.py

AMLOS-532
Make Elasticsearch Updates more efficient for Listing Modifications
Right now every time a listing gets updated it calls Elasticsearch multiple times via the Model Save Hook.  Have it so that it only calls elasticsearch once for each listing modification via the Observer Listing Hook (only gets called once)
Code to make Elasticsearch Updates more efficient for Listing Modifications has been Refactor. 
```
make test_parallel
```
**Checklist**

refactor(es): listing change

---

ozpcenter/api/listing/model_access.py
ozpcenter/api/listing/serializers.py
ozpcenter/api/listing/urls.py
ozpcenter/api/listing/views.py
tests/ozpcenter_model_access/test_listing.py

AMLOS-449
As the administrator, I would like to capture the reason for deleting a listing by requiring the user to submit reason during the deletion process.
1. include feedback form in the deletion process
2. require the user to provide feedback in order to complete the process
Log in as jones
Go to Listing Management > My Listings
Pend a listing for deletion.  Ensure that you are forced to enter a reason.
Log in as bigbrother
Go to the Administration tab of the listing.  Ensure you see the reason set by jones.
Go to Listing Management > Recent Activity.  Ensure you see the reason set by jones.
Checkout `pending_deletion_feedback` from `ozp-center`
Checkout `pending_deletion_feedback` from `ozp-backend`
**Please …

feat(listing): require feedback when pending a listing for deletion

---

ozpcenter/api/listing/observers.py
ozpcenter/api/notification/model_access.py
ozpcenter/api/notification/notifications.py
ozpcenter/models.py
tests/ozpcenter_api/test_api_notification.py

AMLOS-490
"Pend for deletion" request should launch notification to org steward.
Steps to verify:
Pre-req- set jones as owner of Chart Course App
Log on as jones 
Edit Chart Course and set to pend for deletion 
Log on as org steward ( julia) 
RESULTS - Should have a notification that mentions the pending for deletion request.
Pull this branch. Pull  pending_deletion_notification_updates from react commons.
As jones, pend a listing for delete. Bigbrother and julia should receive notification.
As jones, cancel the request. Bigbrother and julia should receive notification.
As jones, pend a listing for delete.
As bigbrother and julia, return the request. Jones should receive a notification
As jones, pend a listing for …

Pending deletion notification updates

---

ozpcenter/api/listing/model_access.py
ozpcenter/api/listing/views.py
tests/ozpcenter/helper.py
tests/ozpcenter_api/test_api_listing.py
tests/ozpcenter_model_access/test_listing.py

AMLOS-545
I would like to capture the reason when an app steward deletes a listing by requiring the app steward to submit a reason during the deletion process.
1. include feedback form in the deletion process
2. require the app steward to provide feedback in order to complete the process
Checkout `delete_listing_feedback` from `ozp-center`
Checkout `delete_listing_feedback` from `ozp-backend`
_Test Scenario 1_
Log in as bigbrother
Delete a listing via Listing Management
Ensure that you are required to enter a reason for deletion
Ensure that the reason displays in Listing Management > Recent Activity
_Test Scenario 2_
Log in as jones
Pend a listing for deletion
Log in as bigbrother
Go to Administration tab of listing …

feat(listing): require feedback when deleting a listing

---

ozpcenter/models.py

AMLOS-571
User submitted a ticket to increase the category description from 255 to a higher value.
User can create or update a description of a category using more than 255 characters
Pull both `category_length_increase` ozp-center & ozp-backend branches
Login as a user that can create/edit categories (bigbrother)
Go to Center Settings -> Categories
Choose a category and click Edit
Verify the dialog box allows for upto 500 characters for the description.
- Says 'Max. 500 characters'
- Typing more than 500 with cause a red error
- Typing < 500 will allow for the user to submit it.
**Checklist**

feat(category_description): increase category description length

---

ozpcenter/api/profile/model_access.py

AMLNG-652
AML 3.0 Storefront has a section for frequently visited applications.  An endpoint needs to be created to allow the storage of viewed/launch applications in the user's profile info. 
End point available to track number of visits to an application by a user
End point available to remove a listing from frequently viewed listings
Check out this branch.  Make the API call to get frequently visited listings, ie
```
curl -X GET --header 'Accept: application/json' --header 'X-CSRFToken: 2QR376YTKa7HvyOR7m9yCb6l1iPizsQcS0tkZilPnvAOGfrDbcEcJkOkAn3z9QAV' 'http://localhost:8001/api/profile/self/listingvisits/frequent/'
```
Ensure that disabled listings do not show up in the results.  If you disable a listing, ensure …

fix(frequently visited listings): remove disabled listings from query

---

ozpcenter/api/storefront/model_access.py
ozpcenter/api/storefront/views.py
tests/ozpcenter_api/test_api_storefront.py
tests/ozpcenter_model_access/test_storefront.py

AMLOS-715
Work roles need to be added to the system so that they can be edited on the user profile.  
An apps mall steward can add, update, delete work roles via API
A user can get a list of work roles in the system
The API call for editing a profile updates the user's work roles
This is a continuation of https://github.com/aml-development/ozp-backend/pull/432
This adds a list of work roles to the `GET /api/metadata` call
**Checklist**

feat(work role): add work roles to metadata API call

---

ozpcenter/wsservice/wsclient.py

AMLOS-741
Send notification to correct user id
Notification is sent to correct user id
Error use to only happen for PKI notifications.  the PKI use created two users but was incomplete
**Checklist**

fix(ws_service): sending notification to correct user id

---

ozpcenter/api/bookmark/model_access.py
ozpcenter/api/bookmark/serializers.py
ozpcenter/models.py
ozpcenter/scripts/sample_data_generator.py
ozpcenter/scripts/test_data/agency.yaml
ozpcenter/scripts/test_data/subscriptions.yaml
ozpcenter/scripts/test_data/system_notification.yaml
tests/ozp/bookmark_helper.py
tests/ozp/test_bookmark_helper.py
tests/ozpcenter_api/test_api_bookmark.py
tests/ozpcenter_api/test_api_library.py

AMLNG-757
Endpoint to create a folder using a single listing (by id)
I can see a purpose in creating a New Folder with a single listing id
Use case: from the listing page, create a new bookmark folder and put the listing in that folder.
```
POST /api/bookmark/
{ 
"title": "Folder 1", 
"type": "FOLDER",
"listing":{"id":1}
}
```
**Checklist**

feat(bookmarks): create a folder with a listing

---

ozpcenter/api/listing/serializers.py
ozpcenter/api/profile/serializers.py
tests/ozpcenter_api/test_api_listing.py

AMLOS-753
As a user I want to view another user's profile to view their contact info, org, avatar, and possibly applications they own.
A user can go to a link (through a listing, or directly) that will display the profile info of another user
Backend support for this ticket.
Pull this branch
You may want to change user avatars via the 3.0 edit profile page
When viewing a listing through the API, verify that the data for each owner contains information about the profile's avatar, or `"avatar": null` if the user does not have one.  Example payload:
```
"owners": [
{
"id": 1,
"user": {
"username": "bigbrother"
},
"display_name": "Big Brother",
"avatar": {
"url": "http://localhost:8001/api/image/1238/",
"id": 1238, …
```

feat(profile): add avatar to short profile serializer

---

ozpcenter/api/bookmark/serializers.py
ozpcenter/api/storefront/serializers.py
ozpcenter/scripts/test_data/listing_types.yaml
ozpcenter/scripts/test_data/listings.yaml
tests/ozpcenter/recommend/test_graph_factory.py
tests/ozpcenter/recommend/test_recommend_es.py
tests/ozpcenter/test_data_util.py
tests/ozpcenter_api/test_api_listing.py
tests/ozpcenter_api/test_api_listing_search_es.py
tests/ozpcenter_api/test_api_listing_similiar.py
tests/ozpcenter_api/test_api_storefront.py

Adds API Listing type ti test_data
Add listing type to bookmark serializer
Add listing type to storefront serializer
Add test listing and resolve any conflicts created
Closes #AMLOS-766
Review additional fields needed for API listings and add them to the backend endpoint.
Pull this branch. Run make dev.
you should see api listing type in metadata
you should see listing type in bookmark api objects
you should see listing type in storefront api objects.
Pull https://github.com/aml-development/frontend/tree/api_listing and view the frontend changes to listing 188 and new listing 189.
**Checklist**

feat(listing): add API listing_type

---

ozpcenter/api/listing/views.py
tests/ozpcenter_api/test_api_listing_activites.py

AMLOS-712
It appears that the current /api/listings/activity API only returns results to users that are admins/stewards (bigbrother for example can see results, but betaraybill receives a forbidden error).  It could be worthwhile to check permissions of the user and filter the results from the API to show updates to any listing that the user has access to.
For example, remove updates for private apps that the user is not in the same org, but show updates for apps that the user can view.
If filtering the current API is too much of a hassle, then a new API, or a 'self' API, could be used in its place.
An API is available that returns updates to apps/listings that is filtering to only listings the user is allowed to see.  No user is forbidden …

feat(listing): filter listing updates per user

---

ozpcenter/api/bookmark/model_access.py
ozpcenter/api/bookmark/views.py
ozpcenter/utils.py
tests/ozpcenter_api/test_api_bookmark.py

AMLOS-747
Filter by Shared / Not-Shared bookmark folders
The bookmark endpoint allows a user to filter the bookmarks seen by shared / not-shared bookmark folders in addition to sorting.
```
make test_parallel
``` 
Show Shared Bookmarks
```
GET /api/bookmark/?is_shared=true
```
Show Non-Shared Bookmarks
```
GET /api/bookmark/?is_shared=false
```
Show Shared and Non-Shared Bookmarks
```
GET /api/bookmark/?is_shared=none
GET /api/bookmark/
```
**Checklist**

feat(bookmarks): filter shared and non-shared

---

.travis.yml
docs/features/elasticsearch_upgrade_2.x_6.x.md
ozpcenter/api/listing/elasticsearch_util.py
ozpcenter/api/listing/model_access_es.py
ozpcenter/recommend/recommend_es.py
ozpcenter/scripts/recommend.py
ozpcenter/scripts/show_es_api_calls.py
requirements.prod.txt
tests/ozpcenter/recommend/test_recommend_es.py
tests/ozpcenter_api/test_api_listing_search_es.py

AMLOS-399
AMLOS-462
Document how upgrading to Elasticsearch 6.x will impact code changes needed
Upgrade to Elasticsearch 6.3.2
Code base has been upgraded to use Elasticsearch 6.3.2
Download Elasticsearch
```
ES_VERSION=6.3.2 
ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.tar.gz
wget ${ES_DOWNLOAD_URL}
tar -xzf elasticsearch-${ES_VERSION}.tar.gz
./elasticsearch-${ES_VERSION}/bin/elasticsearch
```
Create a new python environment
```
rm -rf env
make pyenv
source env/bin/activate
```
Run Unit test and run server 
```
make test_parallel
make dev reindex_es
make run
```
Run Curl Command to test search
```
curl -X GET \ …
```

feat(es): upgrade to elasticsearch 6.3

---

ozpcenter/api/profile/model_access.py
ozpcenter/api/profile/views.py
ozpcenter/api/storefront/model_access.py
ozpcenter/api/storefront/views.py
ozpcenter/recommend/recommend.py

AMLOS-796
Sort By on Most Popular was an after-thought on 2.0. It might not make sense on 3.0, particularly when the data set is limited. We'll either remove the Sort By option, or add the ability to expand out the data set.
Based on discussion around this ticket, the sort behavior on all storefront sections and on profile listings (my listings, frequently visited listings) is changed as follows:
- Sections return listings sorted in their default order
- When a custom ordering is set, those listings are sorted in that custom order
Pull this branch
For testing the frontend,
- Go to the storefront on AML 3.0
- For each _See More_ page, check that the default sort returns listings as expected
- Check that changing the …

fix(storefront): change sort behavior

---

ozpcenter/api/storefront/model_access.py

AMLOS-827
On my Local instance, 
Go to create a listing,
Submit listing named "butterfly", Approve Listing
Refresh Listing appears in the Recently Added.
Now See More
Select the Sort Title: A to Z
Results: My "butterfly" Listing is last instead of 2nd in the grouping. (See screenshot)
Sort needs to be case insensitive.  This behavior is caused because "butterfly" starts with a lower case b.
See More pages on storefront will do a case insensitive sort when sorting by _Title: A to Z_, _Title: Z to A_
Pull this branch
Validate acceptance criteria 
**Checklist**

fix(storefront): case insensitive sorting
