aml-development/ozp-backend

ozpcenter/access_control.py, ozpcenter/api/access_control/tests/test_access_control.py, ozpcenter/api/library/model_access.py, ozpcenter/api/library/tests/test_api_library.py, ozpcenter/api/library/urls.py, ozpcenter/api/listing/filters.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/notification/tests/test_notifications.py, ozpcenter/api/notification/urls.py, ozpcenter/api/profile/filters.py, ozpcenter/api/profile/model_access.py, ozpcenter/api/profile/model_forms.py, ozpcenter/api/profile/tests/test_models_profile.py, ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/tests/test_api_storefront.py, ozpcenter/api/storefront/tests/test_storefront.py, ozpcenter/api/storefront/views.py, ozpcenter/model_access.py, ozpcenter/models.py, ozpcenter/permissions.py, ozpcenter/scripts/sample_data_generator.py, ozpcenter/tests/factories.py, ozpcenter/tests/test_access_control.py, ozpcenter/tests/test_sample_data_generator.py, ozpcenter/tests/test_utils.py, ozpcenter/utils.py
Somewhere along the line some of the ozpcenter .py files got tabs instead of 4 spaces. This commit fixes that.
=> (chore) Untabify ozpcenter files

ozpcenter/models.py
=> fix(models.py): Give org stewards access to the correct set of listings

ozpcenter/scripts/sample_data_generator.py
=> chore(sample data): Update DNs for sample data users so they work with

ozpcenter/auth/pkiauth.py
=> fix(pkiauth.py): Limit new user's usernames to 30 chars or less

.gitignore, ozp/settings.py, requirements.txt
ozp.log file format
````
{"time": "2016-03-16T16:25:49.877114", "message": "creating new user for dn: Jones_jones"}
{"time": "2016-03-16T16:25:49.904239", "message": "created new profile for user jones_jones"}
{"time": "2016-03-16T16:25:49.905525", "message": "creating new user for dn: jones jones'"}
{"time": "2016-03-16T16:25:49.933176", "message": "created new profile for user jones_jones_2"}
{"time": "2016-03-16T16:25:49.936418", "message": "updating issuer dn for user jones"}
{"time": "2016-03-16T16:25:49.939130", "message": "creating new user for dn: This guy has a really really really long DN"}
{"time": "2016-03-16T16:25:49.964547", "message": "created new profile for user this_guy_has_a_really_really_r"}
{"time": "2016-03-16T16:36:05.189404", "message": "Loaded ozpcenter urls"} …
```
=> feat(json_logging): Logs Formatted as JSON

ozpcenter/api/category/model_access.py, ozpcenter/api/category/tests/test_api_category.py, ozpcenter/api/storefront/model_access.py
=> fix(Categories): Categories shown in sorted order

ozpcenter/api/storefront/serializers.py
=> fix(QuickView): Storefront call should return owner display name

ozpcenter/api/image/views.py, ozpcenter/api/listing/views.py, ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/serializers.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/api/notification/views.py, ozpcenter/api/profile/views.py
Issue: #122
Please Review:
@clarkjefcoat 
@tonyalletag
=> fix(Notification): Fixed Delete Authorization

ozpcenter/api/listing/serializers.py
=> fix(listing): Don't duplicate contacts in db on listing create

ozp/logging_formatter.py, ozp/settings.py, ozpcenter/api/image/views.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/listing/views.py, ozpcenter/api/notification/views.py, ozpcenter/api/profile/views.py
Fix for Issue: #123 
Please Review PR:
@tonyalletag 
@clarkjefcoat 
@tdressel (optional)
=> fix(Create/Edit Page): Changing the security marking

ozpcenter/api/profile/model_access.py, ozpcenter/api/profile/tests/test_api_profile.py
Issue https://github.com/ozone-development/ozp-backend/issues/130
=> Sorted stewards

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/tests/test_api_listing.py
This PR is for Issue #135 
Please Review:
@clarkjefcoat 
@tonyalletag
=> fix(Search): Made sure the correct listing are showing in Seach

ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py
- Admin Tab Records for approval truncated
- Eliminated extra modified record for submitted action
=> fix(ListingActivity): Admin tab fixes #141

ozpcenter/api/library/model_access.py, ozpcenter/api/library/tests/test_api_library.py
In reference for issue #144
Please review PR:
@clarkjefcoat 
@rkenyon1969 
@akonsowski  (Optional)
=> fix(Library): Getting User's Library now checks listing enabled state

ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py
For issue: #156 
Please Review:
@clarkjefcoat 
@rkenyon1969
=> fix(listing): Add small_icon to support center #156

ozpcenter/api/library/serializers.py, ozpcenter/api/library/tests/test_api_library.py
Issue: #154 
Please Review:
@clarkjefcoat 
@rkenyon1969
=> fix(library): Ability to bookmark apps that are enabled only #154

ozpcenter/api/library/model_access.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/listing/views.py, ozpcenter/api/storefront/model_access.py, ozpcenter/migrations/0003_listing_is_deleted.py, ozpcenter/models.py
For Issue #48 
Please review:
@clarkjefcoat 
@rkenyon1969
=> feat(listing): Add Listing DELETED to Activity Log #48

ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/models.py
Please Review:
@rkenyon1969 
@clarkjefcoat
=> feat(listing): Ability to see if listing is bookmarked #159

ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/views.py
please review  : 
@mannyrivera2010  
@clarkjefcoat 
@rkenyon1969
=> feat(listing): Users Ability for seeing Recent Activity #167

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/tests/test_api_listing.py
@clarkjefcoat @mannyrivera2010 @rkenyon1969
=> feat(model_access): added a filter to self listings to hide deleted apps

ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/listing/views.py, ozpcenter/scripts/sample_data_generator.py
Please Review:
@rkenyon1969 
@akonsowski
=> fix(listing): Added Search for Listing Tags #170

ozpcenter/api/listing/model_access.py, ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/serializers.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/api/notification/views.py
Please Review Pr:
@akonsowski 
@rkenyon1969 
@wski - Change was made for ozp-center
=> feat(notification): App creators Notifying audience #176

ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/api/notification/views.py
Please Review
@rkenyon1969 
@akonsowski 
@wski
=> feat(notification): Notifications Filtering (All, Pending, Expiring)

ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/tests/test_api_notification.py
Please Review
@rkenyon1969 
@wski 
@akonsowski 
Clarified Requirement from @wski : Only show notifications of the listing if the person has the listing bookmarked
=> fix(notification): App creators notifying audience #176

ozpcenter/api/agency/model_access.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/serializers.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/api/notification/views.py, ozpcenter/migrations/0005_notification_agency.py, ozpcenter/models.py
Stewards Specifying Select Audience
=> feat(Notifications): Stewards Specifying Select Audience #177

.hooks/pre-commit, ozp/logging_formatter.py, ozp/settings.py, ozpcenter/api/agency/model_access.py, ozpcenter/api/category/model_access.py, ozpcenter/api/contact_type/model_access.py, ozpcenter/api/image/views.py, ozpcenter/api/intent/model_access.py, ozpcenter/api/library/views.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/views.py, ozpcenter/api/notification/serializers.py, ozpcenter/api/notification/views.py, ozpcenter/api/profile/views.py, ozpcenter/api/storefront/serializers.py, ozpcenter/errors.py
Please Review
@rkenyon1969 
@akonsowski 
@rkenyon1969 
Issue Below needs to also be completed:
https://github.com/ozone-development/ozp-ansible/issues/20
In reference to #191
=> Clean Code for development ease

.travis.yml, ozp/settings.py, ozpcenter/api/image/serializers.py, ozpcenter/api/image/views.py, ozpcenter/api/library/model_access.py, ozpcenter/api/library/tests/test_api_library.py, ozpcenter/api/library/urls.py, ozpcenter/api/library/views.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/profile/model_access.py, ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/views.py, ozpcenter/errors.py, ozpcenter/model_access.py, ozpcenter/models.py, plugins/default_access_control/main.py, plugins/default_access_control/tests/test_access_control.py, plugins_util/plugin_manager.py, release.py, requirements.txt
Please Review
@akonsowski 
@clarkjefcoat
=> feat(cache): Use Redis for caching #189

ozp/tests/helper.py, ozpcenter/api/library/tests/test_api_library.py, ozpcenter/api/library/views.py, ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/models.py
* Added Unit Test
* Fixed the Library Caching issue
Please Review
@clarkjefcoat 
@akonsowski 
@rkenyon1969
=> chore(notification): Added more unit test #129

ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/tests/test_api_storefront.py, ozpcenter/api/storefront/views.py
Please Review
@akonsowski 
@wski
=> feat(search): Added App list to metadata endpoint #192

ozpcenter/api/library/model_access.py, ozpcenter/api/notification/tests/test_api_notification.py
Please Review
@rkenyon1969 
@wski 
@clarkjefcoat 
@akonsowski
=> fix(notification): Allow Front-end to dismiss notifications #202

ozp/roles_draft.py, ozpcenter/api/listing/views.py, ozpcenter/api/profile/views.py
In Reference to #206 
Please Review
@rkenyon1969 
@clarkjefcoat 
@akonsowski
=> fix(endpoints): Secure Endpoints #206

ozp/settings.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/profile/serializers.py, ozpcenter/api/profile/views.py, plugins/default_access_control/main.py
Please Review
@rkenyon1969 
@akonsowski 
@skhtet
=> feat(plugins): access control dynamic value #208

ozp/settings.py, ozpcenter/api/listing/serializers.py
In Reference to #204 
Please Review
@skhtet 
@rkenyon1969 
@akonsowski
=> feat(listing): Owners Access Control Check #204

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/tests/test_api_review.py
In reference to issue #211
Please Review:
@skhtet 
@akonsowski 
@rkenyon1969
=> fix(reviews): deletes review is showing wrong user 

ozpcenter/api/listing/serializers.py, ozpcenter/api/notification/serializers.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/api/profile/serializers.py
In reference to #213 
Please Review:
@skhtet 
@akonsowski 
@rkenyon1969
=> feat(tailorviews): Anonymized Data #213

ozpcenter/api/profile/serializers.py, ozpcenter/api/profile/views.py
In reference to #216 
Please Review:
@akonsowski 
@rkenyon1969 
@skhtet
=> feat(pki): Add 2dparty Identity #216

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/profile/tests/test_api_profile.py, ozpcenter/api/storefront/model_access.py, ozpcenter/scripts/sample_data_generator.py, plugins/default_access_control/main.py
In Reference to #215 
Please Review:
@rkenyon1969 
@skhtet 
@akonsowski
=> 2PI- Prohibit 2PI users from Submitting/Editing/Owning a Listing

ozpcenter/migrations/0007_auto_20160928_1858.py, ozpcenter/migrations/0008_auto_20160928_1904.py, ozpcenter/models.py
#227 @mannyrivera2010 @akonsowski
=> enhance(tag): increase tag length to 30 #227

ozpcenter/api/storefront/model_access.py
Please review:
@rkenyon1969 
@akonsowski 
@lsemesky 
@skhtet
=> fix(autocomplete): Fix autocomplete to show enabled/approved #229

ozpcenter/api/library/model_access.py, ozpcenter/api/library/serializers.py, ozpcenter/api/library/tests/test_api_library.py, ozpcenter/migrations/0009_applicationlibraryentry_position.py, ozpcenter/models.py
In Reference to #231 
Please Review:
@akonsowski 
@rkenyon1969 
@skhtet 
@lsemesky
=> feat(library): Provide support to sort items on HUD #231

ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/profile/tests/test_api_profile.py, ozpcenter/scripts/sample_data_generator.py, plugins/default_access_control/main.py, requirements.txt
@seenusuvarna @J-Fid @mannyrivera2010 @skhtet
=> feat(listing):added check for each owners certificate

ozpcenter/api/listing/model_access_es.py
Please review
@seenusuvarna 
@lsemesky
=> feat(elasticsearch): Added id field to suggested results

ozpcenter/api/listing/elasticsearch_util.py
Please Review:
@skhtet 
@seenusuvarna 
@lsemesky 
@J-Fid
=> feat(elasticsearch): Included Launch Url into records

elasticsearch/benchmark_process.py, ozp/settings.py, ozpcenter/api/listing/model_access_es.py, ozpcenter/api/listing/tests/test_elasticsearch_util.py
Please Review 
@lsemesky 
@J-Fid 
@seenusuvarna
=> 158 es private app

ozp/settings.py, ozpcenter/api/listing/elasticsearch_util.py, ozpcenter/api/listing/model_access_es.py
Please Review
@seenusuvarna 
@J-Fid 
@rkenyon1969 
@skhtet 
@lsemesky 
Preq:
Preq PR:  https://github.com/aml-development/ozp-ansible/pull/30
=> feat(elasticsearch): Added support for basic auth

ozpcenter/api/listing/elasticsearch_util.py
Please Review:
@seenusuvarna 
@J-Fid 
@skhtet 
@rkenyon1969 
@lsemesky 
Reindex elasticsearch when pulling branch
=> feat(elasticsearch): fixed agency dash search issue

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/views.py, ozpcenter/migrations/0010_auto_20170109_2128.py, ozpcenter/models.py
@mannyrivera2010 @seenusuvarna @J-Fid
=> Pendingdelete

ozpcenter/api/library/model_access.py, ozpcenter/api/library/views.py, ozpcenter/models.py
Please Review:
@akonsowski 
@lsemesky 
@J-Fid 
@seenusuvarna
=> fix(library): Shared Bookmark

ozpcenter/api/storefront/model_access.py, ozpcenter/models.py
Please Review:
@seenusuvarna 
@skhtet 
@J-Fid 
@lsemesky 
Added Securty Filtering for Recommendations
=> feat(recommend): Ensures Security Filtering of Recommendations

ozpcenter/api/listing/elasticsearch_util.py
Please Review:
@J-Fid 
@skhtet 
@lsemesky 
Changes for allowing searching with missing first letter with fuzziness.
=> Fix for searching with first letter missing

Makefile, ozpcenter/recommend/recommend.py, ozpcenter/scripts/recommend.py, ozpcenter/scripts/sample_data_generator.py
Please Review
@lsemesky 
@J-Fid 
@seenusuvarna 
@skhtet
=> Recomender Infrastructure Template Code

Makefile, ozpcenter/recommend/recommend.py
Please Review
@akonsowski 
@seenusuvarna
=> feat(recommend): Added Logger and Elasticsearch Template code

Makefile, ozpcenter/models.py, ozpcenter/recommend/graph.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/tests/test_utils.py, ozpcenter/recommend/utils.py
Added Custom Algorithm for Recommendations
@seenusuvarna 
@J-Fid 
@lsemesky 
@akonsowski
=> Custom Recommender Engine

ozpcenter/recommend/recommend.py
Please Review 
@skhtet 
@seenusuvarna 
@J-Fid
=> feat(recommend): Verbose Progress

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/urls.py, ozpcenter/api/listing/views.py
````
GET /api/listing/1/similar/
Host: 127.0.0.1:8001
Authorization: Basic YmlnYnJvdGhlcjpwYXNzd29yZA==
Content-Type: application/json
Respond:
[
{
Listing Serializer JSON....
},
{ ....
}
]
````
TODO:
Figure out the Similar Listing Algorithm
=> feat(listing): Added Route and Template for Similar Listings

ozpcenter/api/listing/elasticsearch_util.py, ozpcenter/api/listing/model_access_es.py
@seenusuvarna 
@akonsowski 
Please review.
=> fix(elasticsearch): Fixed Tags filtering

ozpcenter/recommend/graph.py, ozpcenter/recommend/pipeline.py, ozpcenter/recommend/pipes.py, ozpcenter/recommend/query.py, ozpcenter/recommend/tests/test_graph.py, ozpcenter/recommend/tests/test_pipeline.py, ozpcenter/recommend/tests/test_query.py, ozpcenter/recommend/tests/test_utils.py, ozpcenter/recommend/utils.py
Please Review
@akonsowski 
@J-Fid 
@seenusuvarna
=> Recommend graph

Makefile, ozpcenter/api/storefront/model_access.py, ozpcenter/models.py, ozpcenter/recommend/graph.py, ozpcenter/recommend/pipeline.py, ozpcenter/recommend/pipes.py, ozpcenter/recommend/query.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/tests/test_pipeline.py, ozpcenter/recommend/tests/test_utils.py, ozpcenter/recommend/utils.py
Please Review:
@seenusuvarna 
@skhtet 
@J-Fid 
@akonsowski
=> feat(recommend):Lazy Security Marking Check and unit tests

ozpcenter/api/listing/elasticsearch_util.py
Please review:
@seenusuvarna 
@akonsowski
=> (fix):Added the ability to search tags.

ozpcenter/pipe/pipeline.py, ozpcenter/pipe/pipes.py, ozpcenter/recommend/algorithms.py, ozpcenter/recommend/graph.py, ozpcenter/recommend/graph_factory.py, ozpcenter/recommend/query.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/tests/test_algorithms.py, ozpcenter/recommend/tests/test_graph.py, ozpcenter/recommend/tests/test_query.py, ozpcenter/recommend/utils.py
Please Review
@J-Fid 
@seenusuvarna
=> Graph  Collaborative Filtering implementation

ozpcenter/api/library/tests/test_api_library.py, ozpcenter/api/listing/elasticsearch_util.py, ozpcenter/api/listing/model_access_es.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_api_listing_activites.py, ozpcenter/api/listing/tests/test_api_search.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/api/notification/tests/test_api_notification.py, ozpcenter/api/profile/tests/test_api_profile.py, ozpcenter/models.py, ozpcenter/pipe/pipes.py, ozpcenter/recommend/graph_factory.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/tests/test_algorithms.py, ozpcenter/recommend/tests/test_graph.py, ozpcenter/recommend/tests/test_graph_factory.py, ozpcenter/recommend/tests/test_query.py, ozpcenter/recommend/tests/test_utils.py, ozpcenter/recommend/utils.py, ozpcenter/scripts/recommend.py, ozpcenter/scripts/sample_data_generator.py
Please Review:
@seenusuvarna 
@mleeBoeing 
@lsemesky 
@J-Fid
=> Graph impl refactor

ozpcenter/api/listing/elasticsearch_util.py
Please Review:
@seenusuvarna 
@J-Fid 
@lsemesky 
@skhtet 
@mleeBoeing
=> fix(elasticsearch): fixed elasticsearch mapping for tags

Makefile, ozp/settings.py, ozpcenter/scripts/recommend.py
Please Review:
@lsemesky 
@J-Fid 
@seenusuvarna 
@mleeBoeing
=> feat(db): Added postgresql to MakeFile and Settings.py

ozpcenter/api/category/model_access.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/tests/test_api_storefront.py, ozpcenter/api/storefront/tests/test_storefront.py, ozpcenter/api/subscription/model_access.py, ozpcenter/api/subscription/serializers.py, ozpcenter/api/subscription/tests/test_api_notification.py, ozpcenter/api/subscription/tests/test_notifications.py, ozpcenter/api/subscription/urls.py, ozpcenter/api/subscription/views.py, ozpcenter/migrations/0016_subscription.py, ozpcenter/models.py, ozpcenter/scripts/sample_data_generator.py, ozpcenter/urls.py
Please Review 
@seenusuvarna 
@lsemesky 
@J-Fid 
@mleeBoeing 
Usage:
````
POST http://localhost:8001/api/subscription/
{"entity_type":"tag", "entity_id":5}
Response
{
"id": 3,
"target_profile": {
"id": 4,
"user": {
"username": "wsmith",
"email": "wsmith@oceania.gov"
},
"display_name": "Winston Smith",
"dn": "Winston Smith wsmith"
},
"entity_type": "tag",
"entity_id": 5,
"entity_description": "tag_2"
}
---------------
POST http://localhost:8001/api/subscription/
{"entity_type":"category", "entity_id":5}
Response
{
"id": 4,
"target_profile": {
"id": 4,
"user": {
"username": "wsmith",
"email": "wsmith@oceania.gov"
},
"display_name": "Winston Smith",
"dn": "Winston Smith wsmith"
},
"entity_type": "category",
"entity_id": 5,
"entity_description": "Entertainment"
}
---------------
GET …
```
=> Subscription

ozpcenter/api/listing/elasticsearch_util.py, ozpcenter/api/listing/model_access_es.py, ozpcenter/api/listing/tests/test_elasticsearch_util.py
@blynch11p 
@seenusuvarna 
Please Review.
=> fix(Able to use special characters when searching).

ozpcenter/api/storefront/model_access.py, ozpcenter/migrations/0017_recommendationsentry_recommendation_data.py, ozpcenter/models.py, ozpcenter/pipe/pipeline.py, ozpcenter/pipe/pipes.py, ozpcenter/pipe/tests/test_pipeline.py, ozpcenter/recommend/algorithms.py, ozpcenter/recommend/graph.py, ozpcenter/recommend/query.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/recommend_utils.py, ozpcenter/recommend/tests/test_recommend_utils.py
Please Review:
@seenusuvarna 
@J-Fid 
@lsemesky 
@mleeBoeing 
@skhtet
=> Recommend table

ozpcenter/pipe/pipeline.py, ozpcenter/pipe/pipes.py, ozpcenter/recommend/algorithms.py, ozpcenter/recommend/query.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/recommend_utils.py, ozpcenter/scripts/recommend.py, ozpcenter/scripts/sample_data_generator.py
Please Review:
@J-Fid 
@skhtet 
@mleeBoeing
=> feat(recommend): Added Collabative Filter to recommend script

ozpcenter/api/storefront/model_access.py
Please Review At
@lsemesky 
@J-Fid 
@seenusuvarna 
@skhtet
=> feat(recommend): Fixed Error incase there are no recommendations

ozpcenter/recommend/recommend.py
Please Review:
@seenusuvarna 
@J-Fid 
@skhtet
=> feat(recommend): Increased Performance via Batching

Makefile, ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/views.py, ozpcenter/pipe/pipes.py, ozpcenter/scripts/sample_data_generator.py
Please Review
@seenusuvarna 
@skhtet 
@lsemesky 
@J-Fid
=> Updated Storefront

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/views.py
please review:
@lsemesky 
@J-Fid
=> fix(similar_listing): Added Lazy loading for listings

ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/views.py
Please Review
@lsemesky 
@skhtet
=> fix(storefront): Reverted back to old way

ozpcenter/migrations/0020_beta_group_script.py, ozpcenter/models.py
Please Review:
@lsemesky 
@seenusuvarna 
@J-Fid 
@skhtet
=> Beta user script

ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/api/listing/tests/test_listing.py, ozpcenter/scripts/sample_data_generator.py, ozpcenter/scripts/test_data/profile.yaml, ozpcenter/tests/test_sample_data_generator.py
Data to go with too_many_tabs branch in ozp-center.  I changed the user with all the orgs to be bettafish.
@lsemesky @mannyrivera2010 @mleeBoeing
=> Too many tabs - data

ozpcenter/api/storefront/model_access.py
This change is to remove the bookmarked items that a user might have also appear in their recommended items.  This will then draw a new recommendation for the user.
To Review changes, please do the following:
Before launching back-end, do the following:
- RUN: make recommend
- Launch Back-End
- See Recommended Items (no bookmarked items should exist)
- Bookmark a Recommended Item that has not been bookmarked already
- **Refresh** the screen and should not see the Bookmarked item in the recommended list
- Can repeat for more Recommended items and they should subsequently disappear from the recommended list and new recommendations should appear.
Please compare load times for AML when reviewing this request and if there are any improvements to the code that you feel might be better, please …
=> Changes to remove bookmarked listings from profile upon retrieval

ozpcenter/api/storefront/model_access.py, ozpcenter/pipe/pipes.py
Please Review
@J-Fid 
@seenusuvarna 
@rkenyon1969 
@mleeBoeing
=> feat(recommend): Added Jittering Pipe for Storefront

ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/tests/test_storefront.py, ozpcenter/api/storefront/views.py, ozpcenter/recommend/recommend.py
Please Review
@skhtet 
@J-Fid 
@mleeBoeing
=> fix(recommend): Fixed Ordering and added scores to entry

ozpcenter/scripts/notification_email.py
Please Review
@skhtet 
@J-Fid 
@mleeBoeing
=> feat(email): Initial Push for Notifications Email

ozpcenter/api/storefront/model_access.py
Please Review 
@seenusuvarna 
@skhtet 
@mleeBoeing
=> feat(recommend): Fixed hardcoded username

ozpcenter/api/storefront/views.py
Please Review
@skhtet 
@seenusuvarna
=> feat(recommend): Fixed typo in storefront

Makefile, ozp/settings.py, ozpcenter/recommend/recommend.py, ozpcenter/scripts/recommend.py
@blynch11p 
This is the changes from #303 ported due to a merge issue that was created.  Please review and give a thumbs up so that I can merge the changes before getting out of sync with the mainline.
Code was tested to ensure similar results were coming as the last commit on the other branch.
=> (es_recommend) Port changes from es_recommend_user branch

ozpcenter/api/category/views.py, ozpcenter/errors.py
Please Review
@seenusuvarna 
@mleeBoeing
=> Category Deletion Validation

.travis.yml, Makefile, ozpcenter/api/profile/model_access.py, ozpcenter/api/profile/serializers.py, ozpcenter/api/storefront/model_access.py, ozpcenter/migrations/0015_notification_script.py, ozpcenter/migrations/0022_profile_email_notification_flag.py, ozpcenter/models.py, ozpcenter/scripts/notification_email.py
Please Review
@seenusuvarna 
@J-Fid 
@mleeBoeing
=> Added Ability to update groups, email flag, stewards groups

ozp/settings.py, ozpcenter/scripts/notification_email.py
Please Review
@skhtet 
@seenusuvarna 
@J-Fid 
@mleeBoeing
=> feat(email): Added Email Varibles to Settings.py

ozpcenter/api/profile/tests/test_api_profile.py, ozpcenter/scripts/test_data/profile.yaml, ozpcenter/tests/test_sample_data_generator.py
Please Review:
@J-Fid 
@seenusuvarna 
@mleeBoeing
=> feat(users): Added Users Doc in yaml

ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/observers.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/notification/model_access.py
Please Review
@tdressel 
@J-Fid 
@seenusuvarna 
@mleeBoeing 
To Test:
wsmith - Subscribe to a category
bigbrother - Create and publish a listing in that category
wsmith - Should get a notification
=> fix(notification): Fixed add_subscription_notification

ozpcenter/api/listing/elasticsearch_util.py, ozpcenter/api/listing/model_access_es.py, ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/serializers.py, ozpcenter/scripts/notification_email.py, ozpcenter/utils.py
Please Review
@J-Fid 
@seenusuvarna 
@rkenyon1969 
@mleeBoeing
=> feat(order): Added Ordering to ES_Search

ozpcenter/api/agency/views.py
Organizations seems to be sorted by their id currently. Would like to see them sorted alphabetically.
Test:
/api/agency
=> feat(organization): Sort organizations by title

ozpcenter/api/listing/elasticsearch_util.py, ozpcenter/api/listing/model_access_es.py
Please Review:
@J-Fid 
@skhtet 
@seenusuvarna 
@mleeBoeing
=> refactor(search): Added Documentation, Corrected Mapping

ozpcenter/api/category/views.py
Change error message from "Can not" to "Cannot" for category deletion.
=> fix(category): Change error message

Makefile, ozpcenter/api/listing/model_access_es.py, ozpcenter/scripts/sample_data_generator.py
Please Review
@seenusuvarna 
@J-Fid
=> feat(sample_data): Added Elasticsearch Mapping Check

ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/urls.py, ozpcenter/api/storefront/views.py
Please Review
@seenusuvarna 
@skhtet 
@J-Fid 
@mleeBoeing 
To test, go to the following link:
http://127.0.0.1:8001/api/storefront/ (any user)
http://127.0.0.1:8001/api/storefront/featured (any user)
http://127.0.0.1:8001/api/storefront/recent  (any user)
http://127.0.0.1:8001/api/storefront/most_popular (any user)
http://127.0.0.1:8001/api/storefront/recommended (as bettafish)
=> Separate Storefront into multiple calls

ozpcenter/api/listing/serializers.py, ozpcenter/api/storefront/serializers.py, ozpcenter/api/storefront/views.py
To Test:
http://127.0.0.1:8001/api/storefront
There should be less fields in each listing
@seenusuvarna 
@lsemesky 
@mleeBoeing
=> refactor(storefront): Simplify Storefront to use less fields

ozpcenter/api/listing/observers.py, ozpcenter/api/notification/model_access.py
Receive notifications:
If change to Listing URL field in Create New Listing Form then notification
If change to Usage Requirements field in Create New Listing Form then notification
If changes to What's New field in Create New Listing Form then notification
If Listing is disabled/enabled in Listing Modal>Administration tab then notification
Should not receive notifications:
POC change
Categories added/removed
Tags added/removed
Resources added/removed
Banners/icons changed
Screenshots added/removed
Security Markings changed
Added or removed as featured listing
=> Revised notification

ozpcenter/api/listing/tests/test_api_es_search.py
Please review the Unit Test fixes that were needed with the changes that were done for prioritizing the Titles over other items.  No functionality changes were done on this PR.
@skhtet 
@blynch11p 
@rkenyon1969 
To test: Retrieve branch and run:
make test
(Note test will take a while approx 20+ min to run)
Can also verify by seeing Travis CI build passes.
=> Title priority test fix

.travis.yml
Fix for the wget failure in travis builds
@mannyrivera2010 @bflanagan78 @skhtet @blynch11p
=> chore(travis): fix es download link

ozpcenter/recommend/recommend.py
Please review the comments that were pulled out of the code and added to a back-end wiki:
https://github.com/aml-development/ozp-backend/wiki
Links added to the code base and no code changes for this code.
Please review:
@skhtet 
@blynch11p 
@rkenyon1969 
@flesher1 
@mleeBoeing
=> feat(doc): Wiki created and links added to code base

ozpcenter/api/listing/serializers.py, ozpcenter/api/storefront/model_access.py, ozpcenter/models.py
Please Review:
@lsemesky 
@mleeBoeing 
@skhtet 
@flesher1
=> refactor(performance): database

ozpcenter/api/notification/model_access.py, ozpcenter/api/notification/serializers.py
Add notification type to API
- Adds the class ListingOwnerNotification
- Includes modifications to API so notificaiton type can be sent
closes ticket #866 in GIT
=> contact the POCs from a listing

ozpcenter/recommend/recommend.py
AMLNG-647
This is a review that will **NOT** be merged in until it is ready to be used.  This review is only to ensure that the code is ready to be merged when it is needed.  A separate ticket will be created to merge the branch to mainline.
Please review
@skhtet 
@blynch11p 
@rkenyon1969 
The changes are that it will use tags and agencies to influence both ES Content and User Based Recommendations.
Test case scenarios:
(In order to allow for the code to run to create the listings every time change WAIT_TIME in recommend/recommend.py from 30 to 0 at line 263 for test purposes only)
Using master with settings above run (USER: BETTAFISH):
> make recommend_es_user
> make run_es
Get ORIGINAL results of the **Recommended** listings that are displayed
Stop Backend and do the …
=> Enhancements for ES Recommender - Adding Tags and Agency

ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/tests/test_api_listing.py, ozpcenter/models.py
change gave_feedback to return actual feedback from request user instead
=> feat(feedback): change gave_feedback to return actual feedback from request user

ozpcenter/api/storefront/model_access.py, tests/ozpcenter_api/test_api_storefront.py
Please Review
@rkenyon1969 
@mleeBoeing 
@lsemesky 
Recommended is displayed for all Users.
=> Remove betauser

ozpcenter/pubsub.py, ozpcenter/recommend/recommend.py, ozpcenter/recommend/recommend_es.py, tests/ozpcenter/test_pubsub.py
AMLNG-831
Increase Unit Test Coverage
Unit Test Coverage has been increase
`make ptest`
**Checklist**
=> refactor(recommend): refactor code, add pubsub test

ozpcenter/api/listing/model_access.py, ozpcenter/api/storefront/model_access.py, tests/ozpcenter/helper.py, tests/ozpcenter_api/test_api_listing_review.py, tests/ozpcenter_api/test_api_profile.py, tests/ozpcenter_model_access/test_storefront.py
AMLNG-821
Increase unit test coverage for backend
Increase the percentage of coverage
make ptest
**Checklist**
=> tests(listing): add test cases for listing reviews

.coveragerc, ozpcenter/api/library/model_access.py, ozpcenter/api/library/views.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/storefront/model_access.py, ozpcenter/pipe/pipes.py, ozpcenter/recommend/recommend_es.py, tests/ozpcenter/pipe/test_pipe.py, tests/ozpcenter/pipe/test_pipeline.py, tests/ozpcenter_api/test_api_root.py, tests/ozpcenter_model_access/test_library.py
AMLNG-837
Add Error Handling Elasticsearch Recommenders
Elasticsearch Recommenders has error handling so that it will not error out
**How to test code**   
`ES_ENABLED=True make recommend`
`make ptest`
**Checklist**
=> fix(recommend): add error handling

.coveragerc, ozpcenter/api/subscription/model_access.py, ozpcenter/pipe/pipeline.py, ozpcenter/recommend/recommend_utils.py, ozpcenter/utils.py, tests/ozpcenter/helper.py, tests/ozpcenter/pipe/test_pipeline.py, tests/ozpcenter/test_utils.py, tests/ozpcenter_api/test_api_subscription.py, tests/ozpcenter_model_access/test_subscription.py
AMLNG-840
Increase Unit Test Coverage
Unit Test Coverage has been increase
`make ptest`
**Checklist**
=> test(subscription): increase code coverage

ozpiwc/api/data/serializers.py, ozpiwc/api/data/urls.py, ozpiwc/api/data/views.py, ozpiwc/api/intent/urls.py, ozpiwc/api/intent/views.py, ozpiwc/api/names/urls.py, ozpiwc/api/system/urls.py, ozpiwc/api/system/views.py, ozpiwc/urls.py, ozpiwc/views.py, tests/ozpiwc/test_api_system.py, tests/ozpiwc/test_data_api.py
**NOT READY**
AMLNG-XXX
Refactor code to use View Sets
Refactor code to use View Sets
```
make ptest
make dev run
curl --request PUT \
--url http://127.0.0.1:8001/iwc-api/self/data/transportation/car7/ \
--header 'authorization: Basic d3NtaXRoOnBhc3N3b3Jk' \
--header 'content-type: application/vnd.ozp-iwc-data-object+json;version=2' \
--data '{"version": "1.0", "permissions": {"name": "security"}, "entity": {"details": {"color": "red"}}, "pattern": "/transportation/car"}'
```
**Checklist**
=> refactor(iwc): refactor code to use viewsets

ozpcenter/api/notification/views.py, tests/ozpcenter_api/test_api_notification.py
Refactor PendingNotificationView and Expired Notification view.
Allows owners of a listing to view current and past notificaitons in the Send Notification tab for a listing they own.
Allows Org Stewards to use API to access all past notifications(to be fixed 3.0)
Adds applicable tests for new security.
Closes #AMLNG-878
AMLNG-878
As an owner of the listing, I have access to the send notifications tab in a listing I own, but I cannot see current or past notifications. I can send new notifications, but cannot see them after I have sent them. 
Allow owners of a listing to view current and past notifications in the Send Notification tab for a listing they own.
Block owners from accessing notifications (Current and past) of a listing they do not …
=> refactor(NotificationAPI): refactor notification get APIs

ozpcenter/api/agency/serializers.py, ozpcenter/api/category/serializers.py, ozpcenter/api/contact_type/model_access.py, ozpcenter/api/contact_type/serializers.py, ozpcenter/api/contact_type/urls.py, ozpcenter/api/contact_type/views.py, ozpcenter/api/image/model_access.py, ozpcenter/api/image/serializers.py, ozpcenter/api/image/views.py, ozpcenter/api/intent/serializers.py, ozpcenter/api/library/urls.py, ozpcenter/api/listing/model_access.py, ozpcenter/api/listing/model_access_es.py, ozpcenter/api/listing/serializers.py, ozpcenter/api/listing/urls.py, ozpcenter/api/listing/views.py, ozpcenter/api/notification/notifications.py, ozpcenter/api/notification/urls.py, ozpcenter/api/profile/views.py, ozpcenter/api/storefront/serializers.py, ozpcenter/api/subscription/urls.py, ozpcenter/models.py, tests/ozpcenter_api/test_api_image.py, tests/ozpcenter_model_access/test_image.py, tests/ozpcenter_model_access/test_listing.py
AMLNG-824
As a PKI user, I get an error 500 while retrieving images
If a PKI user does not have access to the correct security marking, he/she will be receive a 500 error whenever a GET call is made on /api/image/
Users sees a Permission Denied error
`git checkout master && make dev run` 
Goto `/api/image/1` as pmurt, you should see 'too many sql variables error'
`git checkout refactor_20180118`
Goto `/api/image/1` as pmurt, you should see Permission Denied Error
Ensure all unit tests pass
`make ptest`
**Checklist**
=> fix(image): fixed sql too many variables

ozpcenter/api/storefront/model_access.py, ozpcenter/api/storefront/views.py, ozpcenter/recommend/recommend.py, tests/ozpcenter/helper.py, tests/ozpcenter/recommend/test_recommend.py, tests/ozpcenter/recommend/test_recommend_es.py
AMLNG-921
Add Debug Information to recommend endpoint to allow better debugging
Debug Info was added to /api/storefront/recommend/?debug=true
```
git fetch
git checkout recommend_20180123
make dev run
```
Call `http://127.0.0.1:8001/api/storefront/recommended/?debug_recommendations=True`
you should see `recommended_debug` key under results dictionary
**Checklist**
=> feat(recommend): add api recommendation debug dictionary

ozpcenter/recommend/recommend.py
AMLNG-934
Msgpack Postgres Serialization recommendation unpacking issue 
Msgpack Postgres Serialization recommendation unpacking issue has been solved
Preq: Set up postgres
```
make run_psql  # Run Postgres Development Setup
MSGPACK_PUREPYTHON=True make run_psql 
```
Goto `http://127.0.0.1:8001/api/storefront/recommended/`
Should not give any error
**Checklist**
=> fix(msgpack): fix postgres issue when MSGPACK_PUREPYTHON=True

ozpcenter/recommend/recommend.py
AMLOS-548
Refactor Recommender Logic to support old storage format when retrieving records
Recommender Logic to support old storage format when retrieving records is refactored
```
make shell
data = {'Bookmark Collaborative Filtering': {'recommendations': [[2, 2.0], [96, 1.0], [68, 1.0], [69, 1.0], [70, 1.0], [9, 1.0], [10, 1.0], [44, 1.0], [77, 1.0], [14, 1.0], [47, 1.0], [81, 1.0], [82, 1.0], [147, 1.0], [90, 1.0], [101, 1.0], [63, 1.0]], 'ms_took': 359.5185546875, 'weight': 5.0}, 'Baseline': {'recommendations': [[186, 11.5], [10, 10.0], [9, 9.2], [14, 9.0], [82, 9.0], [96, 9.0], [101, 9.0], [158, 9.0], [2, 8.0], [23, 8.0], [30, 8.0], [147, 8.0], [47, 7.0], [70, 7.0], [73, 7.0], [159, 7.0], [162, 7.0], [178, 6.7], …
```
=> refactor(recommend): backwards comaptibility

ozpcenter/api/category/model_access.py, ozpcenter/api/category/serializers.py, ozpcenter/api/category/urls.py, ozpcenter/api/category/views.py, ozpcenter/models.py, tests/ozpcenter_api/test_api_category.py
AMLNG-534
As a developer, I want to be able to access an API so that I can create calls to update multiple listings' categories at once.
- A 'GET' endpoint is created that retrieves listings filtered by Category 
- Filtered Dynamically by role 
If the Role of the user = Admin then show all
If the Role of the user = Org-steward then show listing under that Org  
If the role of the user = regular user then show listing that user owns
- A 'PUT' endpoint is created that updates multiple listing's category values at once.
GET Endpoint
```
GET /api/category/7/listing/ HTTP/1.1
Host: 127.0.0.1:8001
Authorization: Basic am9uZXM6cGFzc3dvcmQ=    # jones
[
{
"unique_name": "applied_ethics_inc.",
"title": "Applied Ethics Inc.", …
```
=> 20180206 bulk category

tests/ozpcenter_api/test_api_notification.py
**Description**  
Quick pull request to make unit tests pass
=> making unit tests pass based on previous changes

ozp/settings.py
AMLOS-550
As a user, I want to be able to log into the application
Allow user to login with Login and Password
Allow user to logout
Allow user to login with PKI Certificate
Pull `authentication_module` from `ozp-backend`
Pull `authentication_module` from `frontend`
_Dev_
Navigate to the home page.  Ensure that you are redirect to login page.
Log in as any user.  Ensure that you are redirected to the home page, the storefront loads properly, and the user's name displays in the nav bar.  Ensure (via Firebug / Dev Tools in chrome) that the JWT token is part of session storage and persisted as a cookie.
Log out via hamburger menu in nav bar.  Ensure that session storage and cookies are cleared.
_Prod_
Navigate to the …
=> feat(authentication): enable cookie fallback for JWT auth

.gitignore, Makefile, ozpcenter/api/listing/model_access.py, ozpcenter/scripts/sample_data_generator.py, ozpcenter/scripts/test_data/listings.yaml, ozpcenter/utils.py, tests/ozpcenter_api/test_api_listing.py, tests/ozpcenter_api/test_api_listing_review.py, tests/ozpcenter_api/test_api_notification.py
AMLOS-575
Need to make reviews have different created_date values and the ability to add review responses to sample data generator 
New Review Response exist under listing `Acoustic Guitar`
Create Request
```
GET http://127.0.0.1:8001/api/listing/1/review/
```
Response should be 
The Created  is different for each review, and one of the reviews have a review response
```
[
{
"id": 5,
"author": {
"id": 21,
"user": {
"username": "charrington",
"email": "charrington@airstripone.com"
},
"display_name": "Charrington",
"dn": "Charrington charrington"
},
"listing": 1,
"rate": 3,
"text": "I love the sound of acoustic guitars rock on",
"edited_date": "2018-03-12T13:55:22.407409Z",
"created_date": …
```
=> 20180307 review

ozp/settings.py, ozpcenter/api/notification/notifications.py, ozpcenter/auth/pkiauth.py, ozpcenter/urls.py, ozpcenter/utils.py, ozpcenter/wsservice/wsclient.py, tests/ozpcenter/auth/test_pki_auth.py, tests/ozpcenter/wsservice/test_wsclient.py
AMLOS-645
Refactor Backend to Integrate with WS Service including Authentication(JWT)
Test will work locally.
* Run backend
* Run aml-ws-service (pull latest code, npm install, npm start)
* Go to `http://127.0.0.1:4200` (aml-ws-service debugging website)
* Sign in using `bigbrother` on `aml-ws-service debugging website`
* Click on `Connect to websocket`
* Run ozp-center, sign in as bigbrother
* Create System Wide Notification
* Notification should come up on  `aml-ws-service debugging website`
**Checklist**
=> Integration

ozpcenter/api/notification/notifications.py, ozpcenter/wsservice/wsclient.py
AMLOS-645
Refactor Backend to Integrate with WS Service including Authentication(JWT)
Refactor Backend to Integrate with WS Service including Authentication(JWT)
Test will work locally.
* Run backend
* Run aml-ws-service (pull latest code, npm install, npm start)
* Go to `http://127.0.0.1:4200` (aml-ws-service debugging website)
* Sign in using `bigbrother` on `aml-ws-service debugging website`
* Click on `Connect to websocket`
* Run ozp-center, sign in as bigbrother
* Create System Wide Notification
* Notification should come up on  `aml-ws-service debugging website`  
**Checklist**
=> feat(jwt): add authentication to calls

ozpcenter/api/storefront/model_access.py
Add ID to contact type in metadata api
**Checklist**
=> feat(metadata): add id to contact types

ozpcenter/api/profile/model_access.py, ozpcenter/api/profile/views.py, tests/ozpcenter_api/test_api_profile_listingvisit.py
AMLOS-716
There are a few use cases where a user may want to clear out one or all of their frequently used applications (Application no longer applies to the user's job, User switches roles).
User can clear out one or all of their frequently visited listings.
Pull `clear_freq_visited` from `ozp-backend`
Pull `clear_freq_visited` from `frontend`
_Testing API Calls_
Test the following API call (via curl, swagger, etc):
```
POST http://localhost:8001/api/profile/self/listingvisits/clear/
```
If a payload with a listing ID (ie `{"listing":{"id":1}}`) is given, then it will set the count to 0 for that listing.  If a payload with no data (ie `{}`) is given, then it will set all listing counts to 0 for that user.
You can …
=>  feat(profile): allow user to clear all freq visited listings

ozpcenter/api/bookmark/model_access.py, ozpcenter/bookmark_helper.py, ozpcenter/scripts/library_to_bookmarks.py, ozpcenter/scripts/sample_data_generator.py
AMLNG-759
Script to transfer OZP 2.0 Bookmarks to AML 3.0 Bookmarks
Script was created to transfer OZP 2.0 Bookmarks to AML 3.0 Bookmarks
Note: can only run once because it will duplicate the same bookmarks
```
make shell
```
```
print(BookmarkEntry.objects.all().delete())
```
```
python manage.py runscript library_to_bookmarks
...
Processing Username: bigbrother
...
['(F) Animals',
' (L) Killer Whale',
' (L) Lion Finder',
' (L) Monkey Finder',
' (L) Parrotlet',
' (L) White Horse',
' (L) Wolf Finder',
'(F) Instruments',
' (L) Acoustic Guitar',
' (L) Electric Guitar',
' (L) Electric Piano',
' (L) Piano',
' (L) Sound Mixer',
' (L) Violin',
'(F) Weather',
' (L) Lightning',
' (L) Snow',
' (L) Tornado',
'(L) Bread …
```
=> feat(bookmarks): add script for library transfer

ozpcenter/api/listing/observers.py, ozpcenter/api/notification/notifications.py, tests/ozpcenter_api/test_api_notification.py
AMLOS-760
Integrate Bookmark/Listing Notifications to 3.0 Bookmark API
notifications hooked up to BookmarkEntry
```
make test_parallel
```
**Checklist**
=> feat(bookmarks): hook up notifications to BookmarkEntry
